MyACTS/Controllers/AdminPanel/RolesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyACTS.Models;
using MyACTS.Controllers.Attributes;
using MyACTS.Data;
using MyACTS.Models.Entities;
using MyACTS.Services;

namespace MyACTS.Controllers;

[Route("Admin/Roles")]
public class RolesController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IAuthenticationService _authService;

    public RolesController(ApplicationDbContext context, IAuthenticationService authService)
    {
        _context = context;
        _authService = authService;
    }

    [Authenticated]
    [Route("")]
    public IActionResult List()
    {
        return View("/Views/AdminPanel/Roles/List.cshtml");
    }
}

MyACTS/Controllers/AdminPanel/UsersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyACTS.Models;
using MyACTS.Controllers.Attributes;
using MyACTS.Data;
using MyACTS.Models.Entities;
using MyACTS.Services;

namespace MyACTS.Controllers;

[Route("Admin/Users")]
public class UsersController : Controller
{
    private readonly ApplicationDbContext _context;
    private readonly IAuthenticationService _authService;

    public UsersController(ApplicationDbContext context, IAuthenticationService authService)
    {
        _context = context;
        _authService = authService;
    }

    [Authenticated]
    [Route("")]
    public IActionResult List()
    {
        return View("/Views/AdminPanel/Users/List.cshtml");
    }
}

MyACTS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyACTS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyACTS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar p-3">
            <img class="navbar-brand" src="~/img/cdac_acts_inverted_logo.svg">
            <partial name="_LoginPartial.cshtml" />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PG-DAC Group 40 (Sept 2022)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyACTS/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyACTS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyACTS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar">
            <img class="navbar-brand" src="~/img/cdac_acts_inverted_logo.svg">
            <partial name="_LoginPartial.cshtml" />
        </nav>
    </header>

    <div class="row main">
        <div class="col-md-3 col-sm-4 col-xs-12 h-100 bg-white">
            <partial name="_Sidebar.cshtml" />
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
            @RenderBody()
        </div>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PG-DAC Group 40 (Sept 2022)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyACTS/Views/Shared/_LayoutFullWidthCentered.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyACTS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyACTS.styles.css" asp-append-version="true" />
</head>
<body class="full-width centered login">
    <header>
        <nav class="navbar">
            <div class="container-fluid">
                <div class="brand-centered">
                    <img class="navbar-brand" src="~/img/cdac_acts_inverted_logo.svg">
                </div>
            </div>
        </nav>
    </header>
    <main class="main d-flex justify-content-center align-items-center">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PG-DAC Group 40 (Sept 2022)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyACTS/Views/Shared/_Sidebar.cshtml
<ul class="list-group bg-white">
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Admin" asp-action="Index">
            Home
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">
            Users
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Roles" asp-action="Index">
            Roles
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Services" asp-action="Index">
            Services
        </a>
    </li>
    <li class="list-group-item">
        <a class="nav-link text-dark" asp-controller="Messages" asp-action="Index">
            Messages
        </a>
    </li>
</ul>